### ISSUE TITLE
Looking nice :)

### ISSUE THREAD

**Issue by DerManoMann** [djairhogeuens/openapi-php#1]
A couple thoughs of the top of my head...
* keeping this repo separate might be really a good idea (as you suggested, iirc)
* tying the version to the OAS version (3.0.2) asks for trouble IMO - what if you need to create a bugfix release...?
* I think it will require PHP 8.1 due to using `new` for nested attributes and also enums?
* there are a few minor things in `composer.json` like PRS-4 autoloading but I guess it works, eh? :)
* Speaking as maintainer of swagger-php I think moving the code into `OpenApi\Attributes\` would be nice to avoid any possible collisions

Finally a question: the spec.json file in the example folder - is that generated or taken from elsewhere? If so, documenting how that was generated would be cool.
Also, pretty printing weould be nice ;)

Enough nitpicking - nice work. My gut feeling is that creating a new, separate library might be simpler, although there could be a lot of code reuse :)

**Comment by DerManoMann** [comment]
Also, it would be cool to give the example code also a namespace - can be anything, really and can be configured for dev in composer.json - for example:
```
  "autoload-dev": {
    "psr-4": {
      "OpenApi\\Example\\": "example/"
    }
  },
```

**Comment by DerManoMann** [comment]
ok, more questions...

Could `BaseMethod` just be `Method`? And Operation typ `$method` as `Method`?
If not, how are `Operation` and `path` linked?

**Comment by DerManoMann** [comment]
> > Just looking at the updates - I think attributes should be in `src/Attributes` and autoload could be simplifyed to something like
> > ```
> >     "autoload": {
> >         "psr-4": {
> >             "OpenApi\\": "src"
> >         }
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ?
> 
> Based on https://getcomposer.org/doc/04-schema.md#psr-4 I don't think this is true?

Why not? It means classes on `src/` are in namespace `OpenApi`. So with an `Attributes` direcory in there, classes inside that would be `OpenApi\\Attributes'.
Have you tried? Its what I've changed it to locally for some mucking about.

**Comment by DerManoMann** [comment]
> I'm still looking for a solution to the attribute nesting though... Any thoughts?

Not really. Only choice would be to have order enforced to indicate relationships. I've seen suggestions about having something of a `'closing' attribute to mark relationships but that is ugly...

**Comment by DerManoMann** [comment]
Either way I think even now there needs to be some place that knows about all valid nesting relationships in order to put things back together.

**Comment by djairhogeuens** [comment]
> > > Just looking at the updates - I think attributes should be in `src/Attributes` and autoload could be simplifyed to something like
> > > ```
> > >     "autoload": {
> > >         "psr-4": {
> > >             "OpenApi\\": "src"
> > >         }
> > >     }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ?
> > 
> > 
> > Based on https://getcomposer.org/doc/04-schema.md#psr-4 I don't think this is true?
> 
> Why not? It means classes on `src/` are in namespace `OpenApi`. So with an `Attributes` direcory in there, classes inside that would be `OpenApi\Attributes'. Have you tried? Its what I've changed it to locally for some mucking about.

Hmm... If I understand the docs correctly, I interpret the following section

> When autoloading a class like Foo\\Bar\\Baz a namespace prefix Foo\\ pointing to a directory src/ means that the autoloader will look for a file named src/Bar/Baz.php and include it if present.

as follows: When autoloading a class like OpenApi\\Attributes\\Get, a namespace prefix OpenApi\\Attributes\\ pointing to a directory src/OpenApi/Attributes/ means that the autoloader will look for a file named src/OpenApi/Attributes/Get.php which is indeed what I want. A namespace prefix OpenApi\\ pointing to a directory src/ means that the autoloader will look for a file named src/Attributes/Get.php which is incorrect.

What I could do is the following: `"OpenApi\\": "src/OpenApi"` and that would work. However, it would also look in my folder for non-attribute classes that are also in the OpenApi namespace which will decrease the performance I think. That's why I prefer to be a bit more specific in the namespace prefix.

**Comment by djairhogeuens** [comment]
As we are not far away from PHP 8.1 being released (later this month), I'd opt to just take that as the required PHP version for this project. I don't think it's very useful to force something else in there at this point.

**Comment by DerManoMann** [comment]
I still disagree on how prs-4 is set up but its not worth arguing about :)
