### ISSUE TITLE
PHP 8.1 enums?

### ISSUE THREAD

**Issue by DerManoMann** [djairhogeuens/openapi-php#5]
With PHP 8.1 required you could convert all consts to enums?

**Comment by DerManoMann** [comment]
Also could add `declare(strict_types=1);` ?

**Comment by djairhogeuens** [comment]
And https://github.com/phpDocumentor/phpDocumentor/issues/3081 is also blocking me from updating the docs.

**Comment by DerManoMann** [comment]
No pressure :)

**Comment by djairhogeuens** [comment]
So, a new version of Psalm has been released containing enum support and phpDocumentor also supports it now. Currently running into PHPStan not supporting enums yet: https://phpstan.org/blog/plan-to-support-php-8-1

**Comment by ymilin** [comment]
Hello, PHPStan released today version 1.3.0 with full support for enums ! https://github.com/phpstan/phpstan/releases/tag/1.3.0

**Comment by djairhogeuens** [comment]
@ymilin thanks for the heads up. I applied it and created a new beta release for this project!
